param(
  [string]$GATA_ROOT = "D:\Mestrado\GATA_2025_2026\Prueba_aislada\ISO_GATA_20260121_130505",
  [string]$OutputRoot = "",
  [string]$RepoRoot = ""
)

$ErrorActionPreference = "Stop"

if([string]::IsNullOrWhiteSpace($OutputRoot) -and $env:GATA_EXTERNAL_OUTPUT_ROOT){
  $OutputRoot = $env:GATA_EXTERNAL_OUTPUT_ROOT
}
if([string]::IsNullOrWhiteSpace($OutputRoot)){
  $OutputRoot = Join-Path $GATA_ROOT "Complementariedad de analisis\Module C\03_outputs"
}

if([string]::IsNullOrWhiteSpace($RepoRoot) -and $env:GATA_REPO_ROOT){
  $RepoRoot = $env:GATA_REPO_ROOT
}
if([string]::IsNullOrWhiteSpace($RepoRoot)){
  $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..\..\..")).Path
}

$modcOut = $OutputRoot
$outDir = Join-Path $modcOut "deliverables_step9"
$bundleDir = Join-Path $outDir "__bundle_stage_runtime"
$legacyBundleDir = Join-Path $outDir "_bundle_payload"
$zipFinal = Join-Path $outDir "ModuleC_ALL_FINAL_deliverables.zip"

New-Item -ItemType Directory -Force -Path $outDir | Out-Null
if(Test-Path $bundleDir){
  try{
    Remove-Item -Recurse -Force $bundleDir -ErrorAction Stop
  } catch {
    # Keep existing bundle directory when removal is denied; downstream Copy-Item -Force will refresh payload.
    $bundleDir = Join-Path $outDir "__bundle_stage_runtime"
  }
}
if(-not (Test-Path $bundleDir)){
  New-Item -ItemType Directory -Force -Path $bundleDir | Out-Null
}

$staleStep9Meta = @(
  (Join-Path $outDir "runtime_closure_decision.md"),
  (Join-Path $outDir "final_manifest.json"),
  (Join-Path $outDir "final_manifest_recursive_audit.tsv"),
  (Join-Path $outDir "final_sha256_checkpoints.txt"),
  (Join-Path $outDir "final_bundle_staleness_audit.tsv"),
  (Join-Path $modcOut "qa\global_audit_status_scan.tsv"),
  (Join-Path $modcOut "qa\global_audit_status_scan.md")
)
foreach($stalePath in $staleStep9Meta){
  if(Test-Path $stalePath){
    Remove-Item -Force $stalePath
  }
}

$staleAuditRows = New-Object System.Collections.Generic.List[object]
function Add-StaleAudit([string]$checkId, [string]$status, [string]$detail){
  $staleAuditRows.Add([pscustomobject]@{
    timestamp = (Get-Date).ToString("s")
    check_id = $checkId
    status = $status
    detail = $detail
  }) | Out-Null
}

$staleBlocked = $false
if(Test-Path $legacyBundleDir){
  Add-StaleAudit "STALE-001" "BLOCKED_STALE_BUNDLE_PAYLOAD" "Legacy _bundle_payload directory exists in deliverables_step9."
  Remove-Item -Recurse -Force $legacyBundleDir
  $staleBlocked = $true
} else {
  Add-StaleAudit "STALE-001" "PASS" "Legacy _bundle_payload directory not present."
}

if(Test-Path $zipFinal){
  $zipHadLegacy = $false
  Add-Type -AssemblyName System.IO.Compression.FileSystem
  $zipRef = [System.IO.Compression.ZipFile]::OpenRead($zipFinal)
  try{
    foreach($entry in $zipRef.Entries){
      if($entry.FullName -match "(^|/)_bundle_payload/"){
        $zipHadLegacy = $true
        break
      }
    }
  } finally {
    $zipRef.Dispose()
  }
  if($zipHadLegacy){
    Add-StaleAudit "STALE-002" "BLOCKED_STALE_BUNDLE_PAYLOAD" "Previous final ZIP contains _bundle_payload entries."
    $staleBlocked = $true
  } else {
    Add-StaleAudit "STALE-002" "PASS" "Previous final ZIP has no _bundle_payload entries."
  }
}

$globalScanPy = Join-Path $RepoRoot "pipeline\global_audit_status_scan.py"
if(Test-Path $globalScanPy){
  & python $globalScanPy --output-root "$modcOut"
}

$failureRootCause = Join-Path $modcOut "qa\failure_root_cause_matrix.md"
if(-not (Test-Path $failureRootCause)){
  $frLines = @(
    "# Failure Root Cause Matrix",
    "",
    "- timestamp: " + (Get-Date).ToString("s"),
    "- producer: run_step9_final_master_pack.ps1",
    "- note: Auto-generated because upstream matrix was missing.",
    "",
    "| Area | Current state | Evidence | Action |",
    "|---|---|---|---|",
    "| Global scan | Pending Step9 final decision | qa/global_audit_status_scan.tsv | Recompute closure decision after scan consumption |",
    "| Scenario audit | Generated by Step7 producer | qa/scenario_audit.tsv | Validate delta and scenario coverage in closure report |",
    "| Manifest/SHA/ZIP | Generated in Step9 | deliverables_step9/* | Verify inclusion of mandatory QA artifacts |"
  )
  $frLines | Set-Content -Encoding UTF8 $failureRootCause
}

$canonCandidates = @(
  (Join-Path $RepoRoot "PIPELINE_CANON_HANDOFF\12_OBJECTIVES_CANON_MODULEC_IECH.md"),
  (Join-Path $RepoRoot "contracts\13_MODULEC_OBJECTIVES_CANON_IECH.md"),
  (Join-Path $RepoRoot "docs\canon\SCIENTIFIC_THRESHOLD_DECLARATION_REGISTER_MODULE_C.md")
)
$canonPaths = @()
foreach($c in $canonCandidates){ if(Test-Path $c){ $canonPaths += $c } }

$requiredRel = @(
  "qa\inputs_resolved.json",
  "qa\run_log.txt",
  "qa\QA_checks.csv",
  "qa\report_auditoria_v2.txt",
  "qa\preflight_report.txt",
  "qa\objectives_canon_alignment_report.tsv",
  "qa\objectives_canon_alignment_report.md",
  "qa\objectives_canon_sha256.txt",
  "qa\path_scope_guard_report.tsv",
  "qa\scientific_validation_gate.tsv",
  "qa\scientific_threshold_evidence_register.tsv",
  "qa\blocked_claims_register.tsv",
  "qa\causal_matrix_scientific_gate_audit.tsv",
  "qa\brief_claim_scientific_gate_audit.tsv",
  "qa\oc03c_base_smoke_contract_gate.tsv",
  "qa\oc03c_path_scope_preflight.tsv",
  "qa\portuguese_aq_input_inventory.tsv",
  "qa\portuguese_aq_file_format_audit.tsv",
  "qa\portuguese_aq_station_inventory.tsv",
  "qa\portuguese_aq_timeseries_inventory.tsv",
  "qa\portuguese_aq_normalization_audit.tsv",
  "qa\portuguese_aq_station_to_unit_assignment.tsv",
  "qa\gfas_era5_vs_portuguese_aq_concordance.tsv",
  "qa\portuguese_aq_validation_gate.tsv",
  "qa\portuguese_aq_claim_disposition.md",
  "qa\territorial_units_validation.tsv",
  "qa\fire_ingestion_audit.tsv",
  "qa\smoke_route_audit.tsv",
  "qa\smoke_route_source_trace_audit.tsv",
  "qa\gfas_era5_presence_audit.tsv",
  "qa\gfas_era5_decoder_audit.tsv",
  "qa\gfas_era5_decoder_backend_audit.tsv",
  "qa\gfas_era5_decoder_daily_spatial_audit.tsv",
  "qa\gfas_era5_decoder_checkpoints.tsv",
  "qa\gfas_pm2p5fire_message_inventory.tsv",
  "qa\gfas_pm2p5fire_portugal_daily_summary.csv",
  "qa\oc03_v11_decoder_contract_validation.tsv",
  "qa\era5_10u10v_inventory.tsv",
  "qa\era5_wind_portugal_xyz.csv",
  "qa\smoke_route_v0_audit.tsv",
  "qa\warning_inventory.tsv",
  "qa\scientific_claim_gate.tsv",
  "qa\population_zonal_audit.tsv",
  "qa\iech_calculation_audit.tsv",
  "qa\iech_reporting_reframe_audit.tsv",
  "qa\iech_reporting_semantics_audit.tsv",
  "qa\recurrence_classification_audit.tsv",
  "qa\territorial_variables_audit.tsv",
  "qa\wrb_integration_audit.tsv",
  "qa\scenario_assumptions.md",
  "qa\scenario_audit.tsv",
  "qa\global_audit_status_scan.tsv",
  "qa\global_audit_status_scan.md",
  "qa\failure_root_cause_matrix.md",
  "tables\municipio_unit_map.csv",
  "tables\smoke_days_unit_2015_2024.csv",
  "tables\smoke_days_nuts3_annual_2015_2024.csv",
  "tables\smoke_day_score_nuts3_daily.csv",
  "tables\smoke_day_score_municipio_daily.csv",
  "tables\portuguese_aq_daily_station_2015_2024.csv",
  "tables\portuguese_aq_daily_unit_2015_2024.csv",
  "tables\smoke_proxy_aq_concordance_by_unit.csv",
  "tables\smoke_days_municipio_2015_2024.csv",
  "tables\pop_unit_2015_2025_2030.csv",
  "tables\pop_municipio_2015_2025_2030.csv",
  "tables\recurrence_unit_2015_2024.csv",
  "tables\recurrence_municipio_2015_2024.csv",
  "tables\IECH_unit_2015_2024.csv",
  "tables\IECH_unit_2015_2024_mean.csv",
  "tables\IECH_municipio_2015_2024.csv",
  "tables\IECH_municipio_2015_2024_mean.csv",
  "tables\IECH_scenarios_2026_2030.csv",
  "tables\IECH_scenarios_unit_2026_2030_mean.csv",
  "tables\IECH_scenarios_municipio_2026_2030.csv",
  "tables\IECH_scenarios_municipio_2026_2030_mean.csv",
  "tables\wrb_context_nuts3.csv",
  "tables\wrb_context_municipio.csv",
  "tables\territorial_context_nuts3.csv",
  "tables\territorial_context_municipio.csv",
  "brief\Brief_Politica_IECH_2030.md",
  "brief\wrb_summary_for_policy_brief.md",
  "brief\causal_matrix\causal_matrix_IECH_NUTS3.csv",
  "brief\causal_matrix\causal_matrix_IECH_NUTS3.json",
  "brief\causal_matrix\causal_matrix_IECH_NUTS3.txt",
  "brief\causal_matrix\causal_matrix_IECH_municipio.csv",
  "brief\causal_matrix\causal_matrix_audit.tsv",
  "brief\causal_matrix\causal_matrix_sha256_checkpoints.txt",
  "brief\deliverables_step8\ModuleC_STEP8_BRIEF_CAUSAL_deliverables.zip",
  "maps\IECH_ModuleC_master.gpkg",
  "deliverables_step9\runtime_scientific_closure_decision.md"
)

$missing = @()
foreach($rel in $requiredRel){
  $src = Join-Path $modcOut $rel
  if(-not (Test-Path $src)){
    $missing += $rel
    continue
  }
  $dst = Join-Path $bundleDir $rel
  $dstParent = Split-Path -Parent $dst
  if(-not (Test-Path $dstParent)){ New-Item -ItemType Directory -Force -Path $dstParent | Out-Null }
  Copy-Item -Force $src $dst
}

if($canonPaths.Count -gt 0){
  foreach($canonPath in $canonPaths){
    $canonName = Split-Path -Leaf $canonPath
    $canonDst = Join-Path $bundleDir ("canon\" + $canonName)
    $canonParent = Split-Path -Parent $canonDst
    if(-not (Test-Path $canonParent)){ New-Item -ItemType Directory -Force -Path $canonParent | Out-Null }
    Copy-Item -Force $canonPath $canonDst
  }
} else {
  $missing += "canon\12_OBJECTIVES_CANON_MODULEC_IECH.md"
}

$decisionPath = Join-Path $outDir "runtime_closure_decision.md"
$qaChecks = Join-Path $modcOut "qa\QA_checks.csv"
$objReport = Join-Path $modcOut "qa\objectives_canon_alignment_report.tsv"
$causalCsv = Join-Path $modcOut "brief\causal_matrix\causal_matrix_IECH_NUTS3.csv"
$scientificDecisionMd = Join-Path $modcOut "deliverables_step9\runtime_scientific_closure_decision.md"

$qaHold = $false
if(Test-Path $qaChecks){
  $qaRows = Import-Csv $qaChecks -Delimiter ';'
  foreach($r in $qaRows){
    if(($r.status + "") -eq "HOLD"){ $qaHold = $true; break }
  }
}

$objHold = $false
if(Test-Path $objReport){
  $objRows = Import-Csv $objReport -Delimiter "`t"
  foreach($r in $objRows){
    $st = ($r.status + "").ToUpper()
    if($st -in @("HOLD","FAIL","NO-GO","BLOCKED")){ $objHold = $true; break }
  }
}

$causalHold = $false
$causalHasThresholdStatus = $false
if(Test-Path $causalCsv){
  $cRows = Import-Csv $causalCsv -Delimiter ';'
  $firstRow = $null
  if($cRows -is [array]){
    if($cRows.Count -gt 0){ $firstRow = $cRows[0] }
  } else {
    $firstRow = $cRows
  }
  if($null -ne $firstRow){
    $causalHasThresholdStatus = ($firstRow.PSObject.Properties.Name -contains "threshold_gate_status")
  }
  foreach($r in $cRows){
    if((($r.qa_flag + "").ToUpper() -eq "HOLD") -or (($r.missing_components + "").Trim() -ne "")){ $causalHold = $true; break }
  }
}
if(-not $causalHasThresholdStatus){
  Add-StaleAudit "STALE-003" "BLOCKED_STALE_BUNDLE_PAYLOAD" "causal_matrix_IECH_NUTS3.csv lacks threshold_gate_status column."
  $staleBlocked = $true
} else {
  Add-StaleAudit "STALE-003" "PASS" "causal_matrix_IECH_NUTS3.csv includes threshold_gate_status."
}

if(-not (Test-Path $scientificDecisionMd)){
  Add-StaleAudit "STALE-004" "BLOCKED_STALE_BUNDLE_PAYLOAD" "runtime_scientific_closure_decision.md missing."
  $staleBlocked = $true
} else {
  Add-StaleAudit "STALE-004" "PASS" "runtime_scientific_closure_decision.md present."
}

$globalBlockers = 0
$globalFilesScanned = 0
$globalScanConsumed = $false
$globalScanTsv = Join-Path $modcOut "qa\global_audit_status_scan.tsv"
if(Test-Path $globalScanTsv){
  $scanRows = Import-Csv $globalScanTsv -Delimiter "`t"
  $globalFilesScanned = ($scanRows | Measure-Object).Count
  $globalScanConsumed = $true
  foreach($r in $scanRows){
    $v = 0
    [void][int]::TryParse(($r.active_blocker_count + ""), [ref]$v)
    $globalBlockers += $v
  }
}

$finalDecision = "GO"
if($missing.Count -gt 0 -or $qaHold -or $objHold -or $causalHold -or $globalBlockers -gt 0){ $finalDecision = "HOLD" }
$decisionLines = @(
  "# Runtime Closure Decision",
  "",
  "- timestamp: " + (Get-Date).ToString("s"),
  "- output_root: `"$modcOut`"",
  "- decision: **$finalDecision**",
  "",
  "## Evidence",
  "- missing_required_artifacts: " + $missing.Count,
  "- qa_gate_has_hold: " + $qaHold,
  "- objectives_gate_has_hold: " + $objHold,
  "- causal_matrix_has_hold_or_missing: " + $causalHold,
  "- global_audit_scan_path: `"$globalScanTsv`"",
  "- global_audit_files_scanned: " + $globalFilesScanned,
  "- global_audit_scan_consumed: " + $globalScanConsumed,
  "- global_audit_active_blockers: " + $globalBlockers,
  "",
  "## Missing Artifacts",
  ($(if($missing.Count -gt 0){ ($missing | ForEach-Object { "- $_" }) } else { "- none" }) -join "`n"),
  ""
)
$decisionLines | Set-Content -Encoding UTF8 $decisionPath

# BEGIN R6K_RUNTIME_CLOSURE_REFRESH
try {
    $R6KRefreshScript = Join-Path $PSScriptRoot "r6k_refresh_runtime_closure_decision.ps1"
    if (Test-Path -LiteralPath $R6KRefreshScript) {
        & $R6KRefreshScript -OutputRoot $modcOut
        if ($null -ne $LASTEXITCODE -and $LASTEXITCODE -ne 0) {
            throw "R6K runtime closure refresh failed with LASTEXITCODE=$LASTEXITCODE"
        }
    } else {
        Write-Warning "R6K refresh script not found: $R6KRefreshScript"
    }
} catch {
    Write-Error "R6K runtime closure refresh failed: $($_.Exception.Message)"
    throw
}
# END R6K_RUNTIME_CLOSURE_REFRESH

$decisionDst = Join-Path $bundleDir "deliverables_step9\runtime_closure_decision.md"
$decisionParent = Split-Path -Parent $decisionDst
if(-not (Test-Path $decisionParent)){ New-Item -ItemType Directory -Force -Path $decisionParent | Out-Null }
Copy-Item -Force $decisionPath $decisionDst

$r6kAuditPath = Join-Path $modcOut "qa\r6k_runtime_closure_refresh_audit.tsv"
if(Test-Path $r6kAuditPath){
  $r6kAuditDst = Join-Path $bundleDir "qa\r6k_runtime_closure_refresh_audit.tsv"
  $r6kAuditParent = Split-Path -Parent $r6kAuditDst
  if(-not (Test-Path $r6kAuditParent)){ New-Item -ItemType Directory -Force -Path $r6kAuditParent | Out-Null }
  Copy-Item -Force $r6kAuditPath $r6kAuditDst
}

$manifestPath = Join-Path $outDir "final_manifest.json"
$manifest = @()
$bundleFiles = Get-ChildItem -Recurse -File $bundleDir | Sort-Object FullName
foreach($f in $bundleFiles){
  $rel = $f.FullName.Substring($bundleDir.Length).TrimStart('\')
  $h = (Get-FileHash -Algorithm SHA256 $f.FullName).Hash
  $manifest += [pscustomobject]@{
    relative_path = ($rel -replace "\\","/")
    bytes = $f.Length
    modified = $f.LastWriteTime.ToString("s")
    sha256 = $h
  }
}
($manifest | ConvertTo-Json -Depth 6) | Set-Content -Encoding UTF8 $manifestPath

$manifestDst = Join-Path $bundleDir "deliverables_step9\final_manifest.json"
$manifestParent = Split-Path -Parent $manifestDst
if(-not (Test-Path $manifestParent)){ New-Item -ItemType Directory -Force -Path $manifestParent | Out-Null }
Copy-Item -Force $manifestPath $manifestDst

$manifestRecursivePath = Join-Path $outDir "final_manifest_recursive_audit.tsv"
$manifestRows = @()
foreach($f in $bundleFiles){
  $rel = $f.FullName.Substring($bundleDir.Length).TrimStart('\') -replace "\\","/"
  $h = (Get-FileHash -Algorithm SHA256 $f.FullName).Hash
  $manifestRows += [pscustomobject]@{
    relative_path = $rel
    bytes = $f.Length
    sha256 = $h
  }
}
$manifestRows | Export-Csv -Path $manifestRecursivePath -Delimiter "`t" -NoTypeInformation -Encoding UTF8

$manifestRecursiveDst = Join-Path $bundleDir "deliverables_step9\final_manifest_recursive_audit.tsv"
Copy-Item -Force $manifestRecursivePath $manifestRecursiveDst

$shaPath = Join-Path $outDir "final_sha256_checkpoints.txt"
$shaLines = @(
  "STEP9_FINAL_MASTER_PACK checkpoint",
  ("timestamp=" + (Get-Date).ToString("s")),
  ("output_root=" + $modcOut),
  ("bundle_root=" + $bundleDir),
  ("decision=" + $finalDecision)
)
foreach($f in $bundleFiles){
  $rel = $f.FullName.Substring($bundleDir.Length).TrimStart('\') -replace "\\","/"
  $h = (Get-FileHash -Algorithm SHA256 $f.FullName).Hash
  $shaLines += ("BUNDLE|" + $rel + "|sha256=" + $h + "|bytes=" + $f.Length)
}
$shaLines | Set-Content -Encoding UTF8 $shaPath

$shaDst = Join-Path $bundleDir "deliverables_step9\final_sha256_checkpoints.txt"
Copy-Item -Force $shaPath $shaDst

$staleAuditPath = Join-Path $outDir "final_bundle_staleness_audit.tsv"
$staleAuditRows | Export-Csv -Path $staleAuditPath -Delimiter "`t" -NoTypeInformation -Encoding UTF8
$staleAuditDst = Join-Path $bundleDir "deliverables_step9\final_bundle_staleness_audit.tsv"
Copy-Item -Force $staleAuditPath $staleAuditDst

if($staleBlocked){
  throw "BLOCKED_STALE_BUNDLE_PAYLOAD"
}

if(Test-Path $zipFinal){ Remove-Item -Force $zipFinal }
Compress-Archive -Path (Join-Path $bundleDir "*") -DestinationPath $zipFinal -Force

Add-Type -AssemblyName System.IO.Compression.FileSystem
$zipRef2 = [System.IO.Compression.ZipFile]::OpenRead($zipFinal)
$newZipHasLegacy = $false
try{
  foreach($entry in $zipRef2.Entries){
    if($entry.FullName -match "(^|/)_bundle_payload/"){
      $newZipHasLegacy = $true
      break
    }
  }
} finally {
  $zipRef2.Dispose()
}
if($newZipHasLegacy){
  Add-StaleAudit "STALE-005" "BLOCKED_STALE_BUNDLE_PAYLOAD" "New final ZIP contains _bundle_payload entries."
  $staleAuditRows | Export-Csv -Path $staleAuditPath -Delimiter "`t" -NoTypeInformation -Encoding UTF8
  throw "BLOCKED_STALE_BUNDLE_PAYLOAD"
}
Add-StaleAudit "STALE-005" "PASS" "New final ZIP has no _bundle_payload entries."
$staleAuditRows | Export-Csv -Path $staleAuditPath -Delimiter "`t" -NoTypeInformation -Encoding UTF8

Write-Host "OK STEP9_FINAL_MASTER_PACK"
Write-Host "OUTDIR =" $outDir
Write-Host "BUNDLE_DIR =" $bundleDir
Write-Host "ZIP_FINAL =" $zipFinal
Write-Host "ZIP_FINAL_SHA256 =" ((Get-FileHash -Algorithm SHA256 $zipFinal).Hash)
Write-Host "DECISION =" $finalDecision
if($missing.Count -gt 0){
  Write-Host "MISSING_COUNT =" $missing.Count
}


